#!/bin/sh


printf '[*] building site\n'

# TODO: clear generated and remake dirstructure

printf '[*] copying permanent files...'

cp -r permanent/** generated

if [ "$?" = 0 ]
then
	printf ' done\n'
else
	printf ' error\n[F] cannot copy permanent files\n'
	exit 3
fi

for file in $(find sources -type f)
do
	python3 scripts/fill.py $file templates/page.html > generated/${file#*/}
	if [ "$?" != 0 ] 
	then
		printf '[F] critical script exited with error\n'
		exit 4
	fi
done

printf '[+] done building site'
