#!/bin/sh

# build - build website
# 
# Originally designed for use in generating https://fcm.andrewyu.org.
# 
# Copyright (C) 2022  Andrew Yu <andrew@andrewyu.org>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


printf '[*] building site\n'

# TODO: clear generated and remake dirstructure

printf '[*] copying permanent files...'

cp -r permanent/** generated

if [ "$?" = 0 ]
then
	printf ' done\n'
else
	printf ' error\n[F] cannot copy permanent files\n'
	exit 3
fi

for file in $(find sources -type f)
do
	python3 scripts/fill.py $file templates/page.html > generated/${file#*/}
	if [ "$?" != 0 ] 
	then
		printf '[F] critical script exited with error\n'
		exit 4
	fi
done

printf '[+] done building site'
